language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sngs-webapp' ]; then cd .. && eval "mv $currentfolder generator-sngs-webapp" && cd generator-sngs-webapp; fi

